name: MobControl
version: 1.0.0
main: me.vicoquincis.mobcontrol.MobControl
api-version: 1.14
authors: [VicoQuinCis]
description: Control (almost) any mob you find!
depend: [LibsDisguises, ProtocolLib]
commands:
  mobcontrol:
    description: "Control any mob you want!"
    usage: "/mobcontrol [add|remove] (player name)"
